### ISSUE TITLE
Can't build on linux 

### ISSUE THREAD

**Issue by zorgoz** [kyleherzog/Blazicons.Generating#2]
Hi there.
Great job you have done, but I was not able to build on in BitBucket pipeline, while had no issues on my Windows. I had tried on my WSL and it is indeed an issue related to Linux:

`CSC : warning CS8785: Generator 'GoogleMaterialDesignGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'DirectoryNotFoundException' with message 'Could not find a part of the path '/tmp/material-design-icons-ce10317ac118470199735acb63e33ece/files/material-design-icons-main/svg/outlined'.'. [/home/user/repo/Blazicons.GoogleMaterialDesign/Blazicons.GoogleMaterialDesign/Blazicons.GoogleMaterialDesign.csproj]`

And indeed:
![image](https://github.com/kyleherzog/Blazicons.Generating/assets/1569170/533f8c83-30af-41fc-894c-1b7b9b1ac030)

`RepoDownloader` is generating path with backslash separator confusing the kernel altogether by making that `svg` segment part of the file name instead of the path:
![image](https://github.com/kyleherzog/Blazicons.Generating/assets/1569170/9383fd73-f897-40a5-adb2-1d5b6be8221b)

I see that you have this line:
(https://github.com/kyleherzog/Blazicons.Generating/blob/d75f021133dd7f25b1df4501205cd55f95988083/Blazicons.Generating/RepoDownloader.cs#L58) But what was your intention with it?

I need this, hence I will create a fix and PR ASAP.
Will you be able to take a look?

**Comment by kyleherzog** [comment]
Thanks for the PR. I merged it into a feature branch and refactored to match how I like to setup my test projects.  These changes are now fully merged into main.

**Comment by zorgoz** [comment]
Ok, thanks. When are you planning to deploy the new version of this package to nuget?

**Comment by kyleherzog** [comment]
A v1.1 beta has been published. Would welcome any feedback on it. Personaly, I should be able to do some testing with it over the next couple days. Once verified, I'll publish the release version.

**Comment by kyleherzog** [comment]
The release version of v1.1 is now available from NuGet.org.
